CREATE TABLE Author (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL
);

CREATE TABLE Book (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_id int REFERENCES Author(id) ON DELETE SET NULL,
    title varchar(100) NOT NULL
);

INSERT INTO Author(name)
VALUES
('Александр Сергеевич Пушкин'),
('Лев Николаевич Толстой'),
('Артур Конан Дойль');

INSERT INTO Book(author_id, title)
VALUES
(1, 'Сказка о царе Салтане'),
(1, 'Евгений Онегин'),
(2, 'Война и мир'),
(2, 'Анна Каренина'),
(3, 'Шерлок Холмс')